# Generated by Django 5.1.3 on 2024-11-27 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='category',
            field=models.CharField(blank=True, choices=[('AC', 'Action'), ('TH', 'Thriller'), ('DR', 'Drama'), ('CO', 'Comedy'), ('RO', 'Romance')], max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='movie',
            name='language',
            field=models.CharField(blank=True, choices=[('ML', 'Malayalam'), ('EN', 'English'), ('HI', 'Hindi'), ('TA', 'Tamil')], max_length=2, null=True),
        ),
    ]
