# Generated by Django 5.1.3 on 2024-11-30 13:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_theater_alter_movie_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='Showtime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_time', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('2:00 PM', '2:00 PM'), ('3:00 PM', '3:00 PM'), ('6:00 PM', '6:00 PM'), ('9:00 PM', '9:00 PM')], max_length=10)),
                ('show_date_start', models.DateField()),
                ('show_date_end', models.DateField()),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.movie')),
                ('theater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='movies.theater')),
            ],
        ),
    ]
