# Generated by Django 5.1.3 on 2024-11-30 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_showtime'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShowTimeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(choices=[('10:00 AM', '10:00 AM'), ('11:00 AM', '11:00 AM'), ('2:00 PM', '2:00 PM'), ('3:00 PM', '3:00 PM'), ('6:00 PM', '6:00 PM'), ('9:00 PM', '9:00 PM')], max_length=10, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='showtime',
            name='show_time',
        ),
        migrations.AddField(
            model_name='showtime',
            name='show_times',
            field=models.ManyToManyField(to='movies.showtimeoption'),
        ),
    ]
