# Generated by Django 5.1.3 on 2024-11-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_showtimeoption_remove_showtime_show_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showtime',
            name='theater',
        ),
        migrations.AddField(
            model_name='showtime',
            name='theaters',
            field=models.ManyToManyField(to='movies.theater'),
        ),
    ]
